apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
 name: ds-one
spec:
  replicas: 2
  template:
   metadata:
    labels:
     system: ReplicaOne
   spec:
    containers:
    - name: nginx
      image: nginx:1.8.1
      ports:
      - containerPort: 80